auth_enabled: false

server:
  http_listen_port: 3100
  grpc_server_max_recv_msg_size: 20971520  

limits_config:
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  per_stream_rate_limit: 10MB
  per_stream_rate_limit_burst: 20MB
  split_queries_by_interval: 15m
  max_query_parallelism: 32
  retention_period: 336h

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s

query_scheduler:
  max_outstanding_requests_per_tenant: 4096

frontend:
  max_outstanding_per_tenant: 4096

query_range:
  parallelise_shardable_queries: true

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

compactor:
  retention_enabled: true
  working_directory: /tmp/compactor
  retention_delete_delay: 2h
  compaction_interval: 10m
  retention_delete_worker_count: 150
  delete_request_store: filesystem