version: "3.9"
services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./scripts/grafana/provisioning:/etc/grafana/provisioning
      - ./scripts/grafana/dashboards:/etc/grafana/demo-dashboards
      - grafana_data:/var/lib/grafana

  loki:
    image: grafana/loki:2.9.2
    ports:
      - 3100:3100
    volumes:
      - ./scripts/loki:/etc/loki
      - loki_data:/loki
    command: -config.file=/etc/loki/config.yml

volumes:
  grafana_data:
  loki_data: